# Generated by Django 4.0.5 on 2022-06-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubetype',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
