# Generated by Django 4.0.5 on 2022-06-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userresults_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresults',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
