# Generated by Django 4.0.5 on 2022-06-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userresults_cubetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresults',
            name='cubetype',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
